# Generated by Django 2.2.6 on 2019-10-26 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [   # 這個變數目的是要跟資料庫做溝通，目的是要告訴資料庫接下來我要執行以下兩個動作
        migrations.CreateModel(  #動作1: 要創建第一個table，叫 Category
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # 若我們在定義欄位時沒有設定 primary key，Django預設會幫我會設定id這個欄位作為我們的primary key
                # AutoField會自動幫我們塞0，1，... 值進去
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(   #動作2: 要創建第二個table，叫 Record
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=300)),
                ('cash', models.IntegerField()),
                ('balance_type', models.CharField(choices=[('收入', '收入'), ('支出', '支出')], max_length=2)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.Category')),
            ],
        ),
    ]
